BOT_TOKEN=YOUR_BOT_TOKEN
CLIENT_ID=1478720048309997688
CLIENT_SECRET=YOUR_DISCORD_CLIENT_SECRET
GUILD_ID=1467092258032582821
VERIFIED_ROLE_ID=YOUR_VERIFIED_ROLE_ID
VERIFY_LOG_CHANNEL_ID=YOUR_VERIFY_LOG_CHANNEL_ID

VERIFY_WEB_URL=https://zylo-discord-bot-production.up.railway.app/verify
VERIFY_CALLBACK_URL=https://zylo-discord-bot-production.up.railway.app/callback

SESSION_SECRET=your_random_secret_here
PORT=3000

MIN_ACCOUNT_AGE_DAYS=30
MAX_ACCOUNTS_PER_IP=1
SPAM_WINDOW_MINUTES=10
MAX_ATTEMPTS_PER_WINDOW=3

PROXYCHECK_API_KEY=YOUR_PROXYCHECK_KEY
